### ISSUE TITLE
Hock testing

### ISSUE THREAD

**Issue by crh3675** [julianduque/node-elasticemail#4]
I am trying to add some testing for attachments and add in the missing SMS functionality but when I make test, this error gets thrown:

````
     Uncaught Error: No Match For: POST /mailer/send?username=user-test&api_key=api-key-test&from=Test%20user&from_email=test%40email.com&to=my%40email.com
````

It seems hock doesn't like the querystring variables appended to the POST request. May have to refactor those tests.

**Comment by julianduque** [comment]
Changed from Hock to Nock
